name: Crowdin Action
# Controls when the action will run. 
on:
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel  
jobs:
  # This workflow contains a single job called "build"
  synchronize-with-crowdin:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2
    
    # Runs the Crowdin action command
    - name: crowdin action
      uses: crowdin/github-action@1.4.10
      with:
        debug_mode: true
        upload_sources: false
        download_translations: true
        download_language: ach

        crowdin_branch_name: main
        localization_branch_name: l10n-in-context

        # global options
        project_id: 528172
        token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
        source: '/*.json'
        translation: '/translated/%two_letters_code%/%original_file_name%'

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
